//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink
    {
        public int DrinkID { get; set; }
        public string Customer { get; set; }
        public string Drink1 { get; set; }
        public string Size { get; set; }
        public Nullable<int> SizeID { get; set; }
    
        public virtual Size Size1 { get; set; }
    }
}
